DROP SCHEMA IF EXISTS core CASCADE;
DROP SCHEMA IF EXISTS directories CASCADE;
DROP SCHEMA IF EXISTS client CASCADE;
DROP SCHEMA IF EXISTS chat CASCADE;
DROP SCHEMA IF EXISTS tg CASCADE;

CREATE SCHEMA core;
CREATE SCHEMA directories;
CREATE SCHEMA client;
CREATE SCHEMA chat;
CREATE SCHEMA tg;